//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageTrainer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lbl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lbl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LanguageTrainer.Resources.Lbl", typeof(Lbl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional filtering options: .
        /// </summary>
        public static string AdditionalFilteringOptions {
            get {
                return ResourceManager.GetString("AdditionalFilteringOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;All&gt;.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All2 {
            get {
                return ResourceManager.GetString("All2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All without new.
        /// </summary>
        public static string AllWithoutNew {
            get {
                return ResourceManager.GetString("AllWithoutNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category: .
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use only from selected.
        /// </summary>
        public static string ChooseOnlySelected {
            get {
                return ResourceManager.GetString("ChooseOnlySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct answer.
        /// </summary>
        public static string CorrectAnswer {
            get {
                return ResourceManager.GetString("CorrectAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created from:.
        /// </summary>
        public static string CreatedFrom {
            get {
                return ResourceManager.GetString("CreatedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created since: .
        /// </summary>
        public static string CreatedSince {
            get {
                return ResourceManager.GetString("CreatedSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created to:.
        /// </summary>
        public static string CreatedTo {
            get {
                return ResourceManager.GetString("CreatedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging to Dropbox.
        /// </summary>
        public static string DropboxLogin {
            get {
                return ResourceManager.GetString("DropboxLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export since:.
        /// </summary>
        public static string ExportSince {
            get {
                return ResourceManager.GetString("ExportSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression:.
        /// </summary>
        public static string Expression {
            get {
                return ResourceManager.GetString("Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression.
        /// </summary>
        public static string ExpressionColumn {
            get {
                return ResourceManager.GetString("ExpressionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expressions.
        /// </summary>
        public static string Expressions {
            get {
                return ResourceManager.GetString("Expressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlashCards Algorithm.
        /// </summary>
        public static string FlashCardsAlgorithm {
            get {
                return ResourceManager.GetString("FlashCardsAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From:.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Translate.
        /// </summary>
        public static string GoogleTranslate {
            get {
                return ResourceManager.GetString("GoogleTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import creation date.
        /// </summary>
        public static string ImportCreationDate {
            get {
                return ResourceManager.GetString("ImportCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import translation creation date.
        /// </summary>
        public static string ImportDefinedDate {
            get {
                return ResourceManager.GetString("ImportDefinedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import/Export.
        /// </summary>
        public static string ImportExport {
            get {
                return ResourceManager.GetString("ImportExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import recently used date.
        /// </summary>
        public static string ImportRecentlyUsedDate {
            get {
                return ResourceManager.GetString("ImportRecentlyUsedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import statistics for new.
        /// </summary>
        public static string ImportStatisticsForNew {
            get {
                return ResourceManager.GetString("ImportStatisticsForNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import statistics for old.
        /// </summary>
        public static string ImportStatisticsForOld {
            get {
                return ResourceManager.GetString("ImportStatisticsForOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include the following expressions: .
        /// </summary>
        public static string IncludeFollowingExpressions {
            get {
                return ResourceManager.GetString("IncludeFollowingExpressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inorrect answer.
        /// </summary>
        public static string InorrectAnswer {
            get {
                return ResourceManager.GetString("InorrectAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language: .
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanguageTrainer.
        /// </summary>
        public static string LanguageTrainer {
            get {
                return ResourceManager.GetString("LanguageTrainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last answer.
        /// </summary>
        public static string LastAnswer {
            get {
                return ResourceManager.GetString("LastAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen.
        /// </summary>
        public static string Listen {
            get {
                return ResourceManager.GetString("Listen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging to Windows Live.
        /// </summary>
        public static string LiveLogin {
            get {
                return ResourceManager.GetString("LiveLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage languages.
        /// </summary>
        public static string ManageLanguages {
            get {
                return ResourceManager.GetString("ManageLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match whole words.
        /// </summary>
        public static string MatchWholeWords {
            get {
                return ResourceManager.GetString("MatchWholeWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New expressions.
        /// </summary>
        public static string NewExpressions {
            get {
                return ResourceManager.GetString("NewExpressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of words in test: .
        /// </summary>
        public static string NumberOfWordsInTest {
            get {
                return ResourceManager.GetString("NumberOfWordsInTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notebook\Section\Page:.
        /// </summary>
        public static string OneNotePath {
            get {
                return ResourceManager.GetString("OneNotePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other options: .
        /// </summary>
        public static string OtherOptions {
            get {
                return ResourceManager.GetString("OtherOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string Prev {
            get {
                return ResourceManager.GetString("Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently used.
        /// </summary>
        public static string RecentlyUsed {
            get {
                return ResourceManager.GetString("RecentlyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize.
        /// </summary>
        public static string Resize {
            get {
                return ResourceManager.GetString("Resize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result:.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse expressions with translations.
        /// </summary>
        public static string ReverseExpressionsWithTranslations {
            get {
                return ResourceManager.GetString("ReverseExpressionsWithTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all translations.
        /// </summary>
        public static string ShowAllTranslations {
            get {
                return ResourceManager.GetString("ShowAllTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show answer.
        /// </summary>
        public static string ShowAnswer {
            get {
                return ResourceManager.GetString("ShowAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show details.
        /// </summary>
        public static string ShowDetails {
            get {
                return ResourceManager.GetString("ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show empty translations.
        /// </summary>
        public static string ShowEmptyTranslations {
            get {
                return ResourceManager.GetString("ShowEmptyTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only selected.
        /// </summary>
        public static string ShowOnlySelected {
            get {
                return ResourceManager.GetString("ShowOnlySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the following languages:.
        /// </summary>
        public static string ShowTranslationsInLanguages {
            get {
                return ResourceManager.GetString("ShowTranslationsInLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spelling statistics.
        /// </summary>
        public static string SpellingStatistics {
            get {
                return ResourceManager.GetString("SpellingStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start training.
        /// </summary>
        public static string StartTraining {
            get {
                return ResourceManager.GetString("StartTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start training without evaluation.
        /// </summary>
        public static string StartTrainingWithoutEvaluation {
            get {
                return ResourceManager.GetString("StartTrainingWithoutEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize with Dropbox.
        /// </summary>
        public static string SyncWithDropbox {
            get {
                return ResourceManager.GetString("SyncWithDropbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize with Windows Live.
        /// </summary>
        public static string SyncWithLive {
            get {
                return ResourceManager.GetString("SyncWithLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        public static string Training {
            get {
                return ResourceManager.GetString("Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training options: .
        /// </summary>
        public static string TrainingOptions {
            get {
                return ResourceManager.GetString("TrainingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train spelling.
        /// </summary>
        public static string TrainSpelling {
            get {
                return ResourceManager.GetString("TrainSpelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        public static string Translate {
            get {
                return ResourceManager.GetString("Translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        public static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        public static string TranslationColumn {
            get {
                return ResourceManager.GetString("TranslationColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use recently used.
        /// </summary>
        public static string UseRecentlyUsed {
            get {
                return ResourceManager.GetString("UseRecentlyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With last incorrect answer.
        /// </summary>
        public static string WithLastIncorrectAnswer {
            get {
                return ResourceManager.GetString("WithLastIncorrectAnswer", resourceCulture);
            }
        }
    }
}
