//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageTrainer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lbl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lbl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LanguageTrainer.Resources.Lbl", typeof(Lbl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Wszystkie&gt;.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Losuj spośród zaznaczonych.
        /// </summary>
        public static string ChooseOnlySelected {
            get {
                return ResourceManager.GetString("ChooseOnlySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia różne.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie do Dropbox&apos;a.
        /// </summary>
        public static string DropboxLogin {
            get {
                return ResourceManager.GetString("DropboxLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eksportuj od: .
        /// </summary>
        public static string ExportSince {
            get {
                return ResourceManager.GetString("ExportSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyrażenie: .
        /// </summary>
        public static string Expression {
            get {
                return ResourceManager.GetString("Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorytm fiszkowy.
        /// </summary>
        public static string FlashCardsAlgorithm {
            get {
                return ResourceManager.GetString("FlashCardsAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z: .
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import/Eksport.
        /// </summary>
        public static string ImportExport {
            get {
                return ResourceManager.GetString("ImportExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanguageTrainer.
        /// </summary>
        public static string LanguageTrainer {
            get {
                return ResourceManager.GetString("LanguageTrainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostatnia odpowiedź.
        /// </summary>
        public static string LastAnswer {
            get {
                return ResourceManager.GetString("LastAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie do Windows Live.
        /// </summary>
        public static string LiveLogin {
            get {
                return ResourceManager.GetString("LiveLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarządzaj językami.
        /// </summary>
        public static string ManageLanguages {
            get {
                return ResourceManager.GetString("ManageLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notatnik\Sekcja\Strona: .
        /// </summary>
        public static string OneNotePath {
            get {
                return ResourceManager.GetString("OneNotePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostatnio użyte.
        /// </summary>
        public static string RecentlyUsed {
            get {
                return ResourceManager.GetString("RecentlyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wynik: .
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokazuj szczegóły.
        /// </summary>
        public static string ShowDetails {
            get {
                return ResourceManager.GetString("ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokaż puste tłumaczenia.
        /// </summary>
        public static string ShowEmptyTranslations {
            get {
                return ResourceManager.GetString("ShowEmptyTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokaż tylko zaznaczone.
        /// </summary>
        public static string ShowOnlySelected {
            get {
                return ResourceManager.GetString("ShowOnlySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statystyka (pisownia).
        /// </summary>
        public static string SpellingStatistics {
            get {
                return ResourceManager.GetString("SpellingStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statystyka .
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizuj z usługą Dropbox.
        /// </summary>
        public static string SyncWithDropbox {
            get {
                return ResourceManager.GetString("SyncWithDropbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizuj z Windows Live.
        /// </summary>
        public static string SyncWithLive {
            get {
                return ResourceManager.GetString("SyncWithLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do: .
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia treningu.
        /// </summary>
        public static string Training {
            get {
                return ResourceManager.GetString("Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tłumaczenie.
        /// </summary>
        public static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uwzględnij już użyte.
        /// </summary>
        public static string UseRecentlyUsed {
            get {
                return ResourceManager.GetString("UseRecentlyUsed", resourceCulture);
            }
        }
    }
}
