//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageTrainer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Msg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Msg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LanguageTrainer.Resources.Msg", typeof(Msg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoryzacja nie powiodła się..
        /// </summary>
        public static string CannotAuthorise {
            get {
                return ResourceManager.GetString("CannotAuthorise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoryzacja nie powiodła się z powodu błędu: {0}..
        /// </summary>
        public static string CannotAuthorise2 {
            get {
                return ResourceManager.GetString("CannotAuthorise2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się wczytać ustawień programu..
        /// </summary>
        public static string CannotLoadSettings {
            get {
                return ResourceManager.GetString("CannotLoadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot synchronize with more than 1 source at the same time!.
        /// </summary>
        public static string CannotSyncFromTwoSourcesAtTheSameTime {
            get {
                return ResourceManager.GetString("CannotSyncFromTwoSourcesAtTheSameTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eksport do usługi Dropbox nie powiódł się!.
        /// </summary>
        public static string DropboxExportFailed {
            get {
                return ResourceManager.GetString("DropboxExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import nie powiódł się!.
        /// </summary>
        public static string ImportFailed {
            get {
                return ResourceManager.GetString("ImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eksport do usługi Live nie powiódł się!.
        /// </summary>
        public static string LiveExportFailed {
            get {
                return ResourceManager.GetString("LiveExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ładowanie....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono żadnych wyrażen zgodnych z podanymi kryteriami..
        /// </summary>
        public static string NoExpressionsFound {
            get {
                return ResourceManager.GetString("NoExpressionsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podana wartość jest już w słowniku.
        /// </summary>
        public static string NotUnique {
            get {
                return ResourceManager.GetString("NotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyszukiwanie zostało zakończone..
        /// </summary>
        public static string SearchHasEnded {
            get {
                return ResourceManager.GetString("SearchHasEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odpowiedziałeś dobrze na {0} i źle na {1} spośród {2} pytań..
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
    }
}
