// <auto-generated />
namespace LanguageTrainer.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddTranslation2Column : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTranslation2Column));
        
        string IMigrationMetadata.Id
        {
            get { return "201303211947036_AddTranslation2Column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
