// <auto-generated />
namespace LanguageTrainer.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddReverseStatisticColumns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddReverseStatisticColumns));
        
        string IMigrationMetadata.Id
        {
            get { return "201305211919498_AddReverseStatisticColumns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
